export const cardTypes = {
  SET_ACTIVE_CARD: "SET_ACTIVE_CARD",
  SET_CURRENT_USER_POSTS: "SET_CURRENT_USER_POSTS",
  SET_CURRENT_POST_COMMENTS: "SET_CURRENT_POST_COMMENTS",
  FETCH_USER_POSTS: "FETCH_USER_POSTS",
  FETCH_COMMENTS_POST: "FETCH_COMMENTS_POST",
  FETCH_END: "FETCH_END",
};
