export const homeTypes = {
  GET_DATA: "GET_DATA",
  SET_TITLE: "SET_TITLE",
  SET_TOKEN: "SET_TOKEN",
  SET_NOTIFICATION: "SET_NOTIFICATION",
  FETCH_START: "FETCH_START",
  FETCH_END: "FETCH_END",
  SET_USERS: "SET_USERS",
  SET_POSTS: "SET_POSTS",
};
